import StorageService from './StorageService'

/**
 * ReportStorageService
 * Handles securely storing ATS and Interview reports generated by the platform/AI.
 */
class ReportStorageService {
  constructor() {
    this.bucket = 'private-user-data'
  }

  /**
   * Generates the storage path for an ATS report.
   * @param {string} userId - The user ID
   * @param {string} jobId - The associated job/application ID
   * @returns {string} - Computed path
   */
  _generateAtsReportPath(userId, jobId) {
    const timestamp = Date.now()
    return `ats-reports/${userId}/${jobId}/report_${timestamp}.pdf`
  }

  /**
   * Generates the storage path for an Interview report.
   * @param {string} userId - The user ID
   * @param {string} interviewId - The associated interview ID
   * @returns {string} - Computed path
   */
  _generateInterviewReportPath(userId, interviewId) {
    const timestamp = Date.now()
    return `interview-reports/${userId}/${interviewId}/summary_${timestamp}.pdf`
  }

  /**
   * Upload an ATS Report (usually done by backend/AI, but available if generated client-side).
   * @param {string} userId - The user ID
   * @param {string} jobId - The job ID
   * @param {File|Blob} file - The report PDF
   * @returns {Promise<{ path: string }>}
   */
  async saveAtsReport(userId, jobId, file) {
    const path = this._generateAtsReportPath(userId, jobId)
    await StorageService.uploadFile(this.bucket, path, file, { cacheControl: '3600' })
    return { path }
  }

  /**
   * Upload an Interview Report.
   * @param {string} userId - The user ID
   * @param {string} interviewId - The interview ID
   * @param {File|Blob} file - The report PDF
   * @returns {Promise<{ path: string }>}
   */
  async saveInterviewReport(userId, interviewId, file) {
    const path = this._generateInterviewReportPath(userId, interviewId)
    await StorageService.uploadFile(this.bucket, path, file, { cacheControl: '3600' })
    return { path }
  }

  /**
   * Gets a temporary signed URL to view a report securely.
   * @param {string} path - The exact path inside the private bucket
   * @returns {Promise<string>} The signed URL
   */
  async getReportUrl(path) {
    return await StorageService.getSignedUrl(this.bucket, path, 60)
  }
}

export default new ReportStorageService()
